### ISSUE TITLE
Hello, Lucraft: the author of Core ID Extender. Here is a question. Please take a look

### ISSUE THREAD

**Issue by 795454** [dangbroitsdon/LucraftCoreIDExtender#1]
Hello, Lucraft: the author of Core ID Extender. I found it during my visit Lucraft: Core ID Extender conflicts with Photoshop

**Comment by dangbroitsdon** [comment]
it shouldn't be conflicting with it because all it does is mixin into another mod, lucraft core, and overwrites the forge registry for superpowers but i mean tis possible to conflict, also what mod? Unless you're talking about the application photoshop, I could not find the mod.
